#! /bin/sh 

if [ $# -eq 0 ]
then
    echo -n "Enter new program name : "
    read progname
else
    progname=$1
fi

echo $progname

FILELIST="`ls blink.*  2>&1 `"

if [ $? -eq 0 ]
then
    for f in $FILELIST
    do
        newname=`echo $f | sed " s/blink/$progname/"`
        if [ "$f" != "$newname" ]
        then
            echo "Renaming $f  to $newname"
            mv $f $newname
        fi
    done
fi

FILELIST="Makefile"
for f in $FILELIST
do
    echo $f
    sed -i -e " s/blink/$progname/g" $f
done
